# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'testdevops'
    repository: 'react-redux'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'



